### ISSUE TITLE
Figure out a name!

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#101]
* Spaceball
* "Wrecked"-angles
* Paddle Duel
* Paddle War
* Paddle Battle
* Paddle Jam
* Astroball
* Space Bars
* Bounce Bounce Revolution
* Paddle Jockeys
* Paddlenauts
* Deathstroid: Mobile Paddle Rocket Warriors

cc @secretrobotron @DevonBird

**Comment by secretrobotron** [comment]
* Crackem Commanders
* Ballistic Bonanza
* Space Bash
* Bash!
* Planetary Federation of Ball Sports

**Comment by secretrobotron** [comment]
> Bounce Bounce Revolution

hahahahahahhahahah

**Comment by secretrobotron** [comment]
Done.

# DEATHSTROID: Mobile Paddle Rocket Warriors
