### ISSUE TITLE
If both paddles get spin powerup, only one works

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#102]
If both paddles manage to get the spin powerup, only one of them will work, but both will be blue. The first one to acquire the powerup will remain blue forever.

**Comment by flukeout** [comment]
Whoa.

**Comment by secretrobotron** [comment]
I made this easy to replicate on latest commit. In console, use: 
```
Debug.player1Powerup_spin();
Debug.player2Powerup_spin();
```

**Comment by flukeout** [comment]
We've changed how spinning works, so this should no longer be a problem.
