### ISSUE TITLE
Integrate awesome transform matrix breakdown code

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#11]
that @Pomax was kind enough to provide!!

http://jsbin.com/qebiqucoxu/edit?html,css,js,output

However, ONE problem. In the physics engine we are using there is no ``skew``. Sometimes a ``skew`` happens as a result of rotating then scaling, so, how can we handle it? Will we have to build a polygon from scratch instead of relying on transforming a rectangle?

**Comment by flukeout** [comment]
Well, we'll have to test it.

**Comment by secretrobotron** [comment]
> Will we have to build a polygon from scratch instead of relying on transforming a rectangle?

Yeah, I think so. If we're using just html/css to construct game objects, this is a bit of a danger, but your shapes will just look wonky. In any tools we write to generate the html/css for us though, we can just be sure the transforms are in the right order.
