### ISSUE TITLE
Two balls in play

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#116]
(see emoji for details)

<img width="1440" alt="screenshot 2018-02-14 12 37 43" src="https://user-images.githubusercontent.com/403231/36219527-bfdd9902-1185-11e8-84cf-cbde55e66262.png">

**Comment by flukeout** [comment]
Are you able to reproduce this at all @secretrobotron ?

**Comment by flukeout** [comment]
I'm going to close this and add it to our launch checklist bug.
