### ISSUE TITLE
Feedback Mar 12

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#139]
* Spin powerup
  * The top+bottom edges of the board glow when the spin powerup is active. Why not the whole border?
* No clip
  * Love it :D
  * There should be some sort of penalty/tax for using it. Like you move slower on the other person's side or something.
* Ghosting
  * Awesome
  * I think we should make it more visually explicit. Maybe instead of faded opacity, make the middle invisible and draw a dotted outline around the ball. I thought about using the "flashing" NES motif, but the effect is too quick to notice.

**Comment by flukeout** [comment]
Nuking since mostly addressed or at least discussed? Let's see how these behave in game situations.
