### ISSUE TITLE
Menu control bugs

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#149]
* Just starting playing around with the new menu controls, trying to break them a bit. If I go to the second row, go all the way to the left until the `grow` powerup is highlighted, hit left a few more times, and then hit down, it chooses the `noclip` powerup, instead of the next row. It looks like the algo tries to find closest buttons, but it doesn't take into account that some of the buttons on the same row can be slightly different heights, and have `y` values that change slightly (I imagine it's the same for the other axis as well).

* Also, if I've got `P1` highlighted, and then hit left, it skips to the next line. But, it should stay on the same row.

* Feels like things should wrap around to the other side when you hit an "end". Like, moving as far as possible to the left, and then going left again should put you on the far right side. Same for up/down.

**Comment by secretrobotron** [comment]
cc @flukeout

**Comment by flukeout** [comment]
Cool yeah, thanks for finding these. I'll take another pass at the algorithm soon.

**Comment by flukeout** [comment]
hey i'm going to close this as the menu works better than at the time that you wrote this. We can always just do the row / column stuff if we feel the need.
