### ISSUE TITLE
Game crashed when two balls were spinning

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#168]
![image](https://user-images.githubusercontent.com/25212/38473646-4af915b6-3b48-11e8-9d9e-3f63ddddf9de.png)

![image](https://user-images.githubusercontent.com/25212/38473649-5486cdd0-3b48-11e8-8092-33a28c369220.png)

**Comment by secretrobotron** [comment]
@flukeout is there a way to get two balls right away? I'd like to test this a bit more...

**Comment by flukeout** [comment]
I'm going to nuke this as I think we've removed all cases when two balls can happen.

**Comment by secretrobotron** [comment]
👍
