### ISSUE TITLE
No controls in pause menu

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#181]
@flukeout I thhhhiiiiink this is broken, but I'm not sure why. It's just blank. There should still be something there, right?

<img width="82" alt="screenshot 2018-04-28 15 55 38" src="https://user-images.githubusercontent.com/403231/39401177-f9e40062-4b0c-11e8-9d92-df1ff608321c.png">

**Comment by secretrobotron** [comment]
Hahahahah that is... the wrong screenshot.

**Comment by secretrobotron** [comment]
<img width="554" alt="screenshot 2018-04-28 17 52 13" src="https://user-images.githubusercontent.com/403231/39401180-04ace5ea-4b0d-11e8-84c9-40e53574cce7.png">

**Comment by flukeout** [comment]
I'm seeing them for the keyboard controls. Will try later when I have access to gamepads again, maybe that's the issue.

**Comment by secretrobotron** [comment]
Yeah, this isn't a thing. Must have just been something wonky during a merge.
