### ISSUE TITLE
Include transforms (and other CSS properties) in our HTML > 3D parser

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#3]
So, if I rotate something via css transforms (like the ground below), our parser doesn't account for that when we magically turn it into a physics body...

![image](https://user-images.githubusercontent.com/25212/30491518-62701610-99f2-11e7-80e7-3589e08dbe0a.png)

**We should account for**

* Rotation
* Translation
* Scale
* Border-radius
  * If something is square with a border radius, safe to make it into a circle

**Comment by secretrobotron** [comment]
Ahhh yeah, great. Those first three should be easy.

It might be better to make decisions about object shape more explicitly though. Were you thinking we would detect circle-like `border-radius` situations and turn them into circles in the physics engine? It might be better to use some markup to say, "this is definitely a circle", so that the graphics engine can do whatever it wants.

**Comment by flukeout** [comment]
Good Q - in the demos it looks like you can round corners on shapes, so we can do that to squares until they are 'round enough' to turn into circles.

![image](https://user-images.githubusercontent.com/25212/30491854-8457789e-99f3-11e7-8f09-be4e93595b1d.png)

**Comment by secretrobotron** [comment]
Oh, interesting! I wonder if that's a polygon, or another primitive. Which example is that?

**Comment by flukeout** [comment]
http://brm.io/matter-js/demo/#rounded

**Comment by secretrobotron** [comment]
Added some rounded corner detection to the converter. I don't love the way we construct shapes from the information that the converter finds. Might need a util function that goes the extra step to create the physics object. Things like `isStatic` and now `chamfer` can be done automatically.

https://github.com/secretrobotron/games/issues/3

**Comment by flukeout** [comment]
I've started some work in ``pong/converter.js`` to make this process better. We need to be able to:

* Create objects from a data structure too...
  * Pass in all of the x,y,height,width & a classname for the DOM element we create
  * In addition to parsing a DOM node
* I made it so we can pass in physics and other options when calling a constructor

**Comment by flukeout** [comment]
I think this is safe to close.
