### ISSUE TITLE
Move Luke's CSS animator over here and add some features

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#4]
This thing is amazing: http://flukeout.com/examples/animations/

Let's pull it over here so that it can be used as a tool as well.

It would be swell to give it a few more features to let you edit frames as well, like [Alistair's Sprite Viking Editor](https://bocoup.com/blog/no-comply-firefox-4-demo) from a while back.

![sprite viking editor](https://static.bocoup.com/blog/no-comply-sprite-viking.png)

**Comment by secretrobotron** [comment]
Let's actually turn this into an "object editor" so that you can give objects features, animations, states, etc. etc. etc. Objects should be able to react to triggers by switching states and switching animation accordingly.

**Comment by secretrobotron** [comment]
Started bringing over the important bits https://github.com/secretrobotron/games/tree/objet-editor

- Still need to do some rewriting based on parameters. But, maybe forgo this option altogether, in favour of using %'s. Then, objects will rely on their physics to govern their position and stuff.
- Maybe can write another editor (or just a panel within this one) that lets you edit animations. Then, rewriting can happen there, instead of being munged into the object state.

**Comment by secretrobotron** [comment]
kk, lots of progress.

Also, just realized I spelled "object" wrong. Goooo me.

**Comment by secretrobotron** [comment]
TODO:

- [ ] add variables to rest of animations (so far only `wobble` uses [variables properly](https://github.com/secretrobotron/games/pull/13/files#diff-36483f2de98eb83c768f6e7f92d3db86R3))
- [ ] write something to actually save object files to disk
- [ ] let user add/remove states in the editor
- [ ] add static sass compiler to build process for export to a game

**Comment by flukeout** [comment]
Nuking for now, let's keep our issues scoped to Battle Pong so we can roll it out.
