### ISSUE TITLE
Notes on physics engine

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#42]
Hey @secretrobotron - I was messing around with how to run the physics simulation more often than once per frame, like we currently do. As discussed, if we only fire once per frame, we run a higher chance of things glitching out when they are moving fast. Currently we have...

```
oneFrame() {
  updatePhysics(durationOfFrame);  // where durationOfFrame is around 16.66 ms
  updatePaddle();
}
```

If we want to increase the physics 'resolution' we can do this...

```
oneFrame() {
  updatePhysics(durationOfFrame/2);
  updatePhysics(durationOfFrame/2);
  updatePaddle();
}
```

Now it runs two finer steps in the physics simulation, but now we run into some problems, like for example...

* When we spin a paddle we apply an angular velocity of .2

Suddenly, with the code above, the paddle spins twice as fast. The reason being is that the velocity it has (.2) is now applied over half of the time span, making it way faster. So, we have to adjust the velocity we apply. We would have to apply 1/2 of the velocity instead, or .1 when we spin the paddle.

**But wait there is more...**

Let's say the paddle is spinning at our new velocity of .1, if we sample it's velocity after every update of the engine we'll see something like...

```
oneFrame() {
  // Coming into this, paddle speed is .1
  updatePhysics(durationOfFrame/2);
  // After one step, speed is let's say .09 because of air friction
  updatePhysics(durationOfFrame/2);
  // After the second step, speed is let's say .08 because of air friction
  updatePaddle();
  // Now it's set to .1 again...
}
```

So there's a problem here, even when we want to continuously spin, the extra steps in our simulation are slowing it down. I _think_ this is bad because the paddle isn't behaving in a way that we want.

Another thing is, I wonder if we have to scale our air friction according to the time spent in each 'simulation' step. I'm not sure - I'll test it out.

So, what we probably want is...

```
oneFrame() {
  updatePhysics(durationOfFrame/2);
  updatePaddle();
  updatePhysics(durationOfFrame/2);
  updatePaddle();
}
```

For every time we update the physics simulation, we want to make sure we are applying the forces we want to the paddle.

I've been able to get the game to behave closer to how it's supposed to while testing while having more physics steps and these are the kinds of conclusions I'm reaching. We should figure out what to do in order to increase the physics steps to something we can change with a variable without changing the feel and behaviour of the game.

**Lastly** we should make these things dependent on the time it took to render the frame. We don't want to just say something like: _"Fire the physics simulation 3 times per request animation frame"_ but rather, fire it every 5ms. We'll have to keep track of how long each frame takes and adjust things accordingly. If we have a 20 second frame, we should fire the simulation 4 times.

Anyway, wanted to write this up. Let me know your thoughts & reactions.

**Comment by flukeout** [comment]
So in looking at this a bit more, if we double the physics framerate we need to...

* Make the rotational velocity 1/2 of the current value (it should only move half as fast per step)
  * Makes sense right? It should spin half the previous distance (angle delta) per step
* Double the force applied to the paddle for move commands
  * This part doesn't make sense to me.
  * I guess since the force is being applied over half of the timespan, it needs to be doubled to have the same effect?
    * You'd think this would just equal out or something.
* Add a new `physicsStep` (or equivalent) function to user-controlled elements that sample the user inputs every time the physics simulation runs and apply the appropriate rotations / forces every frame.

cc @secretrobotron

**Comment by flukeout** [comment]
So, let's say we decide to run physics steps every `8ms` (twice the current rate) - what we need to do is basically keep track of the extra time in each frame.

On average our frames will take 16.666, so that lets us run two physics steps, but we have .666 👿 left over each frame. We need to store that up in an accumulated time bucket, and when it reaches `8ms`, we fire another frame. I don't think this is super important, but it's recommended by people and some articles and makes sense to do. The simulation will stay truer to 'real time' this way.

**Comment by secretrobotron** [comment]
Ok, so, just for some clarity, the loop should be like this (correct where wrong):

1. Hai!
2. Check inputs
3. Make updates to physics objects depends on inputs or other automated processes
4. Update the physics engine
5. Update the renderer
6. Bai!

So, I think your `physicsStep` idea makes a lot of sense, just to try to isolate it from the rest of what's going on. We could then run it as often as we'd like.

The force stuff about the paddle doesn't make a lot of sense to me yet either. But, I think the problem might be in `updatePhysics(durationOfFrame/2);` because `durationOfFrame/2` seems like it should be more precisely measured if we're doing finer resolution or running the physics resolver more than once per frame. I *think* that's what you're [talking about](https://github.com/secretrobotron/games/issues/42#issuecomment-336492666), but maybe write some more pseudocode here like you did above?

The other thing I'm thinking about is that we could just try to let the game run as fast as possible, and try to nail it at 30fps. If our physics engine and rendered updates happen faster than that, we can just let the CPU rest, or choose a higher framerate. That might be a better/different way to resolve this, because everything would still be "in sync", but just running on a clock we can control.

**Comment by flukeout** [comment]
No, not quite... here's what needs to happen

* Hai! Starting `requestAnimationFrame` cycle
* Start a loop, do this however many times you want...
  * Check inputs
  * Make updates to physics objects depends on inputs or other automated processes
  * Update the physics engine
* Update the renderer
*  Bai!

**Comment by secretrobotron** [comment]
One other way we could explore

* Hai! Starting `requestAnimationFrame` cycle
* Check inputs
* Make updates to physics objects depends on inputs or other automated processes **based on delta for frame**
* Update the physics engine **with same delta**
* Update the renderer
* Sleep for remaining time to level out at 30 or 60 fps
* Bai!

**Comment by flukeout** [comment]
@secretrobotron no that won't work ^ because the idea is to sample the physics simulation MORE OFTEN than the framerate we have access to.

**Comment by secretrobotron** [comment]
Ah yeah, sorry. I wonder then if we could measure how many physics frames we think we could do for each graphics frame. Like, attempt to do 5 physics updates for each `rAF`, and check to see if we've run out of time after each. It would basically do "as many physics updates as possible" before giving time back to the renderer.

**Comment by secretrobotron** [comment]
Notes from @modeswitch:

* Use `Performance.now()` to get time instead of `Date.now()`
* Try to lock framerate of physics engine. e.g. if `d=10` and `fps=2`, run physics engine `5` times.
  * But, it's probably *not* the case that we need to adjust our force measurements based on delta (weird)
* Test on Firefox, because frames seem to be varying a lot

**Comment by secretrobotron** [comment]
Looks like the FPS is pretty variable, like 29-49 FPS. So, need to tune the physics engine and do some profiling to nail it.

**Comment by modeswitch** [comment]
I looked through the matter.js source and it's not sub-sampling your physics simulation automatically. So you should be dividing your `dt` into the preferred resolution for your physics simulation (maybe `2ms`?) and running it enough times to avoid issues with fast-moving objects. Once you figure out your timing, you can also set a maximum velocity so you can be sure objects won't pass through other objects.

Also, there was (is?) a bug here https://github.com/liabru/matter-js/issues/148 that might explain the behavior you were seeing. However, I still recommend locking your physics frame rate to help improve simulation stability.

**Comment by flukeout** [comment]
@modeswitch thanks for digging into it! That's me chiming in at the bottom of the issue you were reading. In another branch I've got the game running at `8ms` samples, which removes many of the glitches we were seeing. To do that, we've got to make sure that all of our direct `velocity` setting in our game know how bit the `dt` is, which isn't too hard. The annoying thing seems to be also updating the `frictionAir` properties, which is the part that feels buggy on `matter.js`'s part.

**Comment by modeswitch** [comment]
> To do that, we've got to make sure that all of our direct velocity setting in our game know how bit the dt is

Why is that the case? If you set the velocity to 10 m/s, the simulation should handle that in the update code. It has access to `dt` when you pass it in to the update handler. No?

**Comment by flukeout** [comment]
I think because right now when we set the velocity, we don't provide the time unit. We just say `5` and I think the engine just fills in the rest, so whatever time delta you are using it fills that in. When running the simulation at 60FPS, the delta is roughly 16ms, so our velocity becomes `5 pixels / 16 ms`, however when we increase the sampling time to 120 FPS, then the velocity becomes `5 pixel  / 8 ms` and things go twice as fast.

I think it's because the engine was designed to just run at 60 FPS. Anyway, that's what I've come to believe with my experiences with it so far. It seems to handle applications of force better, we can keep the same values without changing anything, which is nice.

**Comment by modeswitch** [comment]
OK, that's pretty weird. You could resort to applying forces everywhere (Body.force and Body.torque) I suppose?

**Comment by flukeout** [comment]
Yeah, we apply forces for the paddle movement, and I guess we could do the same with the paddle rotation except then we'd have to put in a limiter for 'max rotation velocity' so that the paddle can't spin like crazy so I guess we'd run into the same issue.

**Comment by flukeout** [comment]
OK, what we have now seems to work pretty well. We are able to set the number of physics steps we want to simulate per frame and things seems to be working well when we change that number.
