### ISSUE TITLE
Notes on Reactions

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#45]
First of all getting a kick out of all this stuff `window.ReactionMachine`, `thick-n-white`.. lol

Anyway a few things I noticed...

* ~~The reactions often seem reversed, when player 1 scores, player 2 shows a 'happy'~~
* I think we should either just show one reaction at a time, or when we show two, stagger them a bit

* ~~Let's ditch the words~~
* ~~We should rename the SVGs so they're easier to work with in the code~~
* I think we should show the reactions a little less frequently
  * Maybe only when a 'score' gets more than 10% of terrain
* If we double-up a reaction (one in short succession after another) we should clear out the first one so that there's never an overlap.

**Comment by flukeout** [comment]
**Reaction Scenarios**
* Round lost
* Reacting to getting 'killed' at the end
  * We could show a permanent 'shaking scared' reaction type?
* Hard shot scored
* Good save made
  * Maybe when close to own end zone and ball speed is high?
* Powerup received
* Scored on self

**Comment by secretrobotron** [comment]
Awesome list. Based on what we talked about yesterday, we can add more for extra-cool powerup moves, but let's start with these ^^ for now.

Might want to add modifiers so that things events like "Round lost" are more visible. e.g. leave the reaction on screen longer, or make it bigger to induce more shame.

**Comment by flukeout** [comment]
Keeping open for now — what do you think @secretrobotron anything we want to try here?

**Comment by flukeout** [comment]
We could add unique ones for when you get a powerup for example to help reinforce them. Let's chat about this one @secretrobotron
