### ISSUE TITLE
"Battle Pong" text still visible when game is running.

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#46]
During a 'background flash' when a player scores.

![image](https://user-images.githubusercontent.com/25212/31577479-2277b818-b0c4-11e7-8ba5-a36f6d94828c.png)

cc @secretrobotron

**Comment by secretrobotron** [comment]
Hahaha oops. I think that'll be fixed when the rest of the menu stuff is done. I'll make sure.

**Comment by flukeout** [comment]
I pushed a small fix for that.
