### ISSUE TITLE
Develop a scene editor

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#6]
We're going to need a good way to set up scenes or levels, procedurally or otherwise. We should have an editor that lets you drop objects on a page, and gives you the markup to make it real in the "engine".

**Comment by secretrobotron** [comment]
Work started in [this branch](https://github.com/secretrobotron/games/tree/scene-editor).

TODO:
- [ ] Turn logic into proper javascript objects. It's quickly becoming spaghetti.
- [ ] Add logic to anchors and sides of selector to resize objects.
- [ ] Implement a simple inspector for selected objects. Should show important aspects and let you edit them, including arbitrary `data-` attributes and classes that can be picked up by the game engine.
- [ ] Implement an inspector for the stage that lets you pick things like BG color, size, etc.
- [ ] Implement some kind of loader to pull in game `css` or `js` so that you can build that separately from the scene editor
- [ ] Implement rotation mode for selected objects
- [ ] Add a timeline editor
- [ ] Implement sequencing

**Comment by flukeout** [comment]
Closin'
