### ISSUE TITLE
Play feedback from Nov 27

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#66]
* Pinning the other player with your paddle is actually a fun strategy to keep them from rushing back to prevent scoring. Wonder if we can emphasize that.
* Powerup idea: zap back to your goal to try to hit the ball in time
* It's easy to spin the wrong direction if you're not used to playing. Wonder what we can do about that.
* Often, the ball gets stuck behind you and you score on yourself a lot. We need a bit of built-in mercy. Maybe the ball zaps back to the middle after a few quick scores, or the loss % is lower for very quick successive scoring.
* Skins for paddles to differentiate because in chaotic moments, it's hard to tell who's who. One could just be black.
* When there are too many balls, it's way too chaotic to even be competitive. We need to remove those balls somehow after a period of time. Maybe after they score? How are they removed right now already?

**Comment by secretrobotron** [comment]
Multiball chaos:

<img width="1440" alt="screenshot 2017-11-27 14 00 50" src="https://user-images.githubusercontent.com/403231/33292255-720281ac-d37d-11e7-8900-8f8aa96305f4.png">

**Comment by secretrobotron** [comment]
* We took out the spin powerup already, but we should try to put it back in. It's a great "advanced player" feature. You can really fool each other.

**Comment by flukeout** [comment]
From this, the one piece we haven't addressed that well is the 'ball stuck behind paddle thing' so I'll close this as I think it's reflected in a more recent issue.
