### ISSUE TITLE
Player feedback from Full Indy Demo Night

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#67]
* People felt that paddle movement was a bit slow and they were chasing the ball a lot
  * One idea to alleviate this is to add a dash feature, allowing players to quickly move in a direction, but penalize them with a little pause in movement after.
  * They could also use this ability for offensive shots.

* People didn't really seem to know how to use the powerups or what they did, how can we encourage people?
* People didn't really know what to do on the finish screen, how can we improve this?
  * We should also increase the drama / tension / effect of getting a finishing shot.

cc @secretrobotron - anything you noticed worth adding? Thoughts on the above?

**Fixed Stuff Below**

* ~~Spin powerup was confusing, people didn't know what it did or when they could use it. It goes away too quickly after you activate it, so I didn't even have time to explain.~~
  * ~~@bernk had a good suggestion of just keeping the power-up on all the time after getting it until it expires so you always control the ball, then you lose it when...~~
    * ~~The timer runs out on it or,~~
    * ~~The opposing player gets it.~~

**Comment by bernk** [comment]
Have you guys tried using up/down instead of left/right to spin the paddle? I think to me this would make it a lot easier (up for cw, down for ccw).

**Comment by flukeout** [comment]
Nope, hadn't thought about that. Only tried the one way that we have implemented now. We'll give it a shot, I guess another way to think of it would be, if you hold down, you want to hit with the bottom of the paddle, and up for the top? So that way it would be different depending on the side you were on. Anyway, we should test @bernk's idea.

**Comment by secretrobotron** [comment]
That pretty much covers it, I think. People were talking about sound enhancements though. Effects and music need work.

**Comment by flukeout** [comment]
Also...

* Give some warning before a bone disappears. People were noticing that they wanted to use them to attack but they would disappear just before hitting the ball, which was annoying.
