### ISSUE TITLE
Firefox Battle Pong issues

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#69]
* ~The board expands when effects occur because Firefox tries to render `outline` CSS around everything in the world. We can solve this by using `border` instead.~
* Gamepads don't use the `mapping` setting...
* `~Shadows don't have the right depth~
* ~Some poerups seem to have an "outline"~
* ~Powerups don't hover~
* Aliasing

... 🤦‍♀️ 

**Edit by @flukeout** - addressed some of these in my latest gh-pages branch. Overall, still visibly less performant than Chrome.

**Comment by secretrobotron** [comment]
* Intro music doesn't start at the right time

**Comment by secretrobotron** [comment]
* It's noticeably slower for some reason. Feels like the physics is much slower, or the framerate has dropped. Maybe we should add a framerate monitor in the settings somehow.

**Comment by secretrobotron** [comment]
@flukeout if you try `http://localhost:8080/?showFrameRate=true` on the latest branch, what does the FPS monitor report for you in Chrome & Firefox? Mine is ~60 for Chrome and ~45 for Firefox...

**Comment by flukeout** [comment]
I'll take a stab at some of these issues over the weekend. I'm getting about 57/58 FPS on Firefox vs Chrome's 61/60 (according to your FPS counter). I'm running the Nightly build of Firefox.

**Comment by flukeout** [comment]
I've found the problem with the Flat powerups, we need to specify `preserve-3d` on the world element, which Chrome doesn't seem to need. Another funny thing I uncovered is that our ball, and probably the powerups too, are being set as squares in the engine, as seen here...

![image](https://user-images.githubusercontent.com/25212/33519219-6f48100c-d757-11e7-8c12-03473bc78180.png)

**Comment by flukeout** [comment]
There's also some kind of problem with the CSS for the powerup shadows, it's not applying the `border-radius` property correctly...

![image](https://user-images.githubusercontent.com/25212/33519402-8e07a130-d75a-11e7-8cbb-283d930235f6.png)

If you modify the property in the developer tools (even making one percent different then going back to the original) then it displays properly, super weird. I think best move is to go with an SVG background image for the circular shadows to avoid this.

**Comment by flukeout** [comment]
The skeleton bones have an `:after` element that the bone background is put onto. Firefox is having trouble rendering this properly. It won't position the background in the pseudo element, and also clips it, as seen here...

![image](https://user-images.githubusercontent.com/25212/33519691-bebbd1ba-d760-11e7-96ae-935d2a6e44c3.png)

Super frustrating, the clipping stops if you like, toggle a rule off and on again in the dev tools. Might have to make this a non-pseudo element instead.

**Comment by flukeout** [comment]
Firefox also positions powerups off-center. They are slightly to the right of where they should be on the middle border between the two colored areas.

**Comment by flukeout** [comment]
Fuck it, let's not worry about this too much.
