### ISSUE TITLE
BUG: Double-speed paddle spinning

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#87]
Sometimes when a new round starts, the player paddle spins twice as fast. Here's a GIF showing it happening, and then slowing down again when the browser is reset:

* https://giphy.com/gifs/xULW8jgTrz55uLYIWQ

Happening to player 1 via keyboard controls. When this happens to player 1, player 2 still spins normally.

cc @secretrobotron 

It's happening in the latest `gh-pages` branch.

**Comment by secretrobotron** [comment]
This was really, really, really hard to reproduce. I still couldn't do it consistently, but I capped the angular velocity properly. I saw that it was being capped *before* all of the other update stuff, so any capping would just be ignored. Let's see if that works.

**Comment by secretrobotron** [comment]
@flukeout I patched gh-pages. Can you check that it's better now?

**Comment by secretrobotron** [comment]
I haven't seen this again since.
